image: node:18

stages:
  - lint
  - build
  - deploy

before_script:
  - npm config set cache .npm --global
  - npm ci --prefer-offline

lint_frontend:
  stage: lint
  script:
    - npm run lint

build_frontend:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 week

deploy_frontend:
  stage: deploy
  script:
    - echo "Deploying frontend application"
    - docker-compose down
    - docker-compose build
    - docker-compose up -d
