image: node:18

stages:
  - install
  - lint
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/ # Cache the npm cache directory instead of node_modules
  policy: pull-push

before_script:
  - npm config set cache .npm --global # Use a local directory for npm cache

install_dependencies:
  stage: install
  script:
    - npm ci --prefer-offline # Use the cached packages if available

lint_frontend:
  stage: lint
  script:
    - npm run lint
  needs:
    - install_dependencies

build_frontend:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 week
  needs:
    - install_dependencies

test_frontend:
  stage: test
  script:
    - npm run test
  needs:
    - install_dependencies
