image: node:18

stages:
  - install
  - lint
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm ci

lint_frontend:
  stage: lint
  needs: ["install_dependencies"]
  script:
    - npm install next
    - npm run lint

build_frontend:
  stage: build
  needs: ["install_dependencies"]
  script:
    - ls node_modules/.bin
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 week

test_frontend:
  stage: test
  needs: ["install_dependencies"]
  script:
    - npm run test
