image: node:18

stages:
  - lint
  - build

before_script:
  - npm config set cache .npm --global
  - npm ci --prefer-offline

lint_frontend:
  stage: lint
  script:
    - npm run lint

build_frontend:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 week
