image: node:18

stages:
  - install
  - lint
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
  policy: pull-push

before_script:
  - npm config set cache .npm --global

install_dependencies:
  stage: install
  script:
    - npm ci --prefer-offline
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

lint_frontend:
  stage: lint
  script:
    - ls -la # Debug: List files and directories in the current working directory
    - ls -la node_modules/.bin # Debug: List files in node_modules/.bin
    - npm run lint
  needs:
    - install_dependencies

build_frontend:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 week
  needs:
    - install_dependencies

test_frontend:
  stage: test
  script:
    - npm run test
  needs:
    - install_dependencies
